INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (1,3,'Dell Pro 1',250.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (2,8,'Dell Pro 2',260.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (3,12,'Dell Pro 3',270.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (4,6,'Dell Pro 4',280.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (5,9,'Dell Pro 5',290.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (6,1,'Mac Book Pro 1',255.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (7,10,'Mac Book Pro 2',265.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (8,12,'Mac Book Pro 3',285.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (9,9,'Mac Book Pro 4',290.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (10,3,'Mac Book Pro 5',300.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (11,8,'Acer Pro 1',210.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (12,11,'Acer Pro 2',220.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (13,9,'Acer Pro 3',230.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (14,10,'Acer Pro 4',240.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (15,11,'Acer Pro 5',250.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (16,7,'LeNovo Pro 1',275.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (17,11,'LeNovo Pro 2',280.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (18,10,'Avel Pro 1',260.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (19,13,'Avel Pro 2',270.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (20,12,'Hp Pro 1',270.5);
INSERT INTO tb_produto(id,estoque,nome,preco) VALUES (21,20,'Hp Pro 2',280.5);